[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
actix-web = "4.9.0"

serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.11"

